### ISSUE TITLE
Wrong formula for Lyne Hollick method

### ISSUE THREAD

**Issue by Kaye-HQ** [tsamsonov/grwat#13]
The current formula you using for Lyne Hollick method seems to be quick flow, rather than baseflow.
see Lyne Hollick,1979,Stochastic Time-Variable Rainfall-Runoff Modeling
![image](https://github.com/tsamsonov/grwat/assets/72720762/484697bb-fef2-458e-a01f-223df38dae6d)

**Comment by Kaye-HQ** [comment]
![image](https://github.com/tsamsonov/grwat/assets/72720762/c1c39cd1-f05d-42bc-aaf9-a665c5a4bb7a)

**Comment by tsamsonov** [comment]
Hi @Kaye-HQ , the issue is actually with function name, not with the formula. A you can see in `get_baseflow_recursive` function [here](https://github.com/tsamsonov/grwat/blob/b0dfa0b183ba222579a1efcfa091bd80b378882c/src/grwat_core.cpp#LL221C38-L221C38) the value returned by `baseflow_lyne` is interpreted as a quick flow, i.e. as you expected. Therefore `gr_baseflow` R interface returns correct value of the baseflow. I'll probably have to fix the function name in the next release of the package.

**Comment by Kaye-HQ** [comment]
All right, Thanks:)
